### ISSUE TITLE
训练好的模型在修改后的测试集上运行报错

### ISSUE THREAD

**Issue by 27182812** [lixin4ever/E2E-TBSA#16]
您好，我在laptop14数据集上训练好了一个模型，想要看看在我自己的数据集上的效果。我根据测试集的格式标注了几句，用训练好的模型进行测试会报如下错误
![屏幕截图 2020-12-22 232531](https://user-images.githubusercontent.com/33630730/102905116-a4368700-44ad-11eb-8470-71d938e330a2.png)
我感觉这个不是我数据的问题，因此我将原有测试集删除了几行运行，同样也报错了。请问测试集的数量是需要设置的吗？
后面我想到了可以替换，于是我将原测试集后6句替换为自己标注的数据，运行后报错如下：
![image](https://user-images.githubusercontent.com/33630730/102905442-1dce7500-44ae-11eb-961d-267f3f6fdf02.png)
请问这是什么原因导致的啊？

**Comment by 27182812** [comment]
第一个截图：
Use pre-trained word embeddings...
Traceback (most recent call last):
  File "main.py", line 253, in <module>
    model = Model(params=args, vocab=vocab, embeddings=embeddings, char_embeddings=char_embeddings)
  File "/home/dc2-user/qys/E2E-TBSA-master/model.py", line 202, in __init__
    self.emb = WDEmb(pc=self.pc, n_words=len(vocab), dim_w=self.dim_w, pretrained_embeddings=embeddings)
  File "/home/dc2-user/qys/E2E-TBSA-master/model.py", line 50, in __init__
    self.W.init_from_array(pretrained_embeddings)
  File "_dynet.pyx", line 1168, in _dynet.LookupParameters.init_from_array
  File "_dynet.pyx", line 1178, in _dynet.LookupParameters.init_from_array
Exception: too many rows

第二个截图：
Traceback (most recent call last):
  File "main.py", line 267, in <module>
    model.decoding(dataset=test, model_name='laptop14_0.566153.model')
  File "/home/dc2-user/qys/E2E-TBSA-master/model.py", line 416, in decoding
    self.pc.populate(model_path)
  File "_dynet.pyx", line 1461, in _dynet.ParameterCollection.populate
  File "_dynet.pyx", line 1516, in _dynet.ParameterCollection.populate_from_textfile
RuntimeError: Dimensions of lookup parameter /_0/_0 lookup up from file ({300,4738}) do not match parameters to be populated ({300,4739})

**Comment by lixin4ever** [comment]
这个repo还不支持把训练好的模型直接apply到其他数据集(或者未知数据)上预测，你可以参考我们的另一个[repo](https://github.com/lixin4ever/BERT-E2E-ABSA)，已经支持了这个功能
