### ISSUE TITLE
执行main.py报错:NotImplementedError

### ISSUE THREAD

**Issue by Evaoooos** [lixin4ever/E2E-TBSA#9]
In Epoch 1 / 50 (current lr: 0.0010):
Traceback (most recent call last):
  File "main.py", line 257, in <module>
    final_res_string, model_path = run(dataset=[train, val, test], model=model, params=args)
  File "main.py", line 51, in run
    loss, pred_ote_labels, pred_ts_labels = model.forward(x=train_set[i], is_train=True)
  File "/data/E2E-TBSA/model.py", line 302, in forward
    stm_lm_hs = [self.stm_lm(h) for h in ote_hs]
  File "/data/E2E-TBSA/model.py", line 302, in <listcomp>
    stm_lm_hs = [self.stm_lm(h) for h in ote_hs]
  File "/data/E2E-TBSA/model.py", line 139, in __call__
    Wx = self._W * x
  File "_dynet.pyx", line 1859, in _dynet.Expression.__mul__
NotImplementedError

谢谢

**Comment by lixin4ever** [comment]
Please refer to this issue [https://github.com/clab/dynet/issues/1386](https://github.com/clab/dynet/issues/1386)

Feel free to post message here if it does not work.

**Comment by Evaoooos** [comment]
its settled thanks~
